version: '3.8'

services:

  sherwin-service:
    image: sherwin-service 
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  
